/**
 * The jurisdictions covered by the national pipeline: all 50 states plus DC,
 * minus Utah (which has its own bespoke fetcher against le.utah.gov).
 *
 * GENERATED FILE — do not hand-edit. Regenerate with:
 *
 *   node scripts/build-jurisdictions.ts
 *
 * Field meanings and provenance are documented in that script.
 */

export interface Jurisdiction {
  /** Uppercase postal code, matching the keys of `src/config/states.ts`. */
  code: string;
  /** Lowercase postal code, used for `openstates/people` directory names. */
  postal: string;
  /** URL slug, matching `src/config/states.ts` and `src/data/<slug>/`. */
  slug: string;
  stateName: string;
  /** e.g. "Massachusetts General Court" — used for source attribution. */
  legislatureName: string;
  /** Official homepage, used as the fallback link for anything without its own URL. */
  url: string;
  /** OCD jurisdiction id for the OpenStates v3 API. */
  jurisdictionId: string;
  /** Nebraska and DC: one body, so roles carry chamber "legislature". */
  unicameral: boolean;
}

export const JURISDICTIONS: Jurisdiction[] = [
  {
    code: "AK",
    postal: "ak",
    slug: "alaska",
    stateName: "Alaska",
    legislatureName: "Alaska State Legislature",
    url: "https://www.akleg.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:ak/government",
    unicameral: false,
  },
  {
    code: "AL",
    postal: "al",
    slug: "alabama",
    stateName: "Alabama",
    legislatureName: "Alabama Legislature",
    url: "https://www.legislature.state.al.us",
    jurisdictionId: "ocd-jurisdiction/country:us/state:al/government",
    unicameral: false,
  },
  {
    code: "AR",
    postal: "ar",
    slug: "arkansas",
    stateName: "Arkansas",
    legislatureName: "Arkansas General Assembly",
    url: "https://www.arkleg.state.ar.us",
    jurisdictionId: "ocd-jurisdiction/country:us/state:ar/government",
    unicameral: false,
  },
  {
    code: "AZ",
    postal: "az",
    slug: "arizona",
    stateName: "Arizona",
    legislatureName: "Arizona State Legislature",
    url: "https://www.azleg.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:az/government",
    unicameral: false,
  },
  {
    code: "CA",
    postal: "ca",
    slug: "california",
    stateName: "California",
    legislatureName: "California State Legislature",
    url: "https://leginfo.legislature.ca.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:ca/government",
    unicameral: false,
  },
  {
    code: "CO",
    postal: "co",
    slug: "colorado",
    stateName: "Colorado",
    legislatureName: "Colorado General Assembly",
    url: "https://leg.colorado.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:co/government",
    unicameral: false,
  },
  {
    code: "CT",
    postal: "ct",
    slug: "connecticut",
    stateName: "Connecticut",
    legislatureName: "Connecticut General Assembly",
    url: "https://www.cga.ct.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:ct/government",
    unicameral: false,
  },
  {
    code: "DC",
    postal: "dc",
    slug: "district-of-columbia",
    stateName: "District of Columbia",
    legislatureName: "Council of the District of Columbia",
    url: "https://dccouncil.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/district:dc/government",
    unicameral: true,
  },
  {
    code: "DE",
    postal: "de",
    slug: "delaware",
    stateName: "Delaware",
    legislatureName: "Delaware General Assembly",
    url: "https://legis.delaware.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:de/government",
    unicameral: false,
  },
  {
    code: "FL",
    postal: "fl",
    slug: "florida",
    stateName: "Florida",
    legislatureName: "Florida Legislature",
    url: "https://www.leg.state.fl.us",
    jurisdictionId: "ocd-jurisdiction/country:us/state:fl/government",
    unicameral: false,
  },
  {
    code: "GA",
    postal: "ga",
    slug: "georgia",
    stateName: "Georgia",
    legislatureName: "Georgia General Assembly",
    url: "https://www.legis.ga.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:ga/government",
    unicameral: false,
  },
  {
    code: "HI",
    postal: "hi",
    slug: "hawaii",
    stateName: "Hawaii",
    legislatureName: "Hawaii State Legislature",
    url: "https://www.capitol.hawaii.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:hi/government",
    unicameral: false,
  },
  {
    code: "IA",
    postal: "ia",
    slug: "iowa",
    stateName: "Iowa",
    legislatureName: "Iowa General Assembly",
    url: "https://www.legis.iowa.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:ia/government",
    unicameral: false,
  },
  {
    code: "ID",
    postal: "id",
    slug: "idaho",
    stateName: "Idaho",
    legislatureName: "Idaho State Legislature",
    url: "https://www.legislature.idaho.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:id/government",
    unicameral: false,
  },
  {
    code: "IL",
    postal: "il",
    slug: "illinois",
    stateName: "Illinois",
    legislatureName: "Illinois General Assembly",
    url: "https://www.ilga.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:il/government",
    unicameral: false,
  },
  {
    code: "IN",
    postal: "in",
    slug: "indiana",
    stateName: "Indiana",
    legislatureName: "Indiana General Assembly",
    url: "https://www.in.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:in/government",
    unicameral: false,
  },
  {
    code: "KS",
    postal: "ks",
    slug: "kansas",
    stateName: "Kansas",
    legislatureName: "Kansas State Legislature",
    url: "https://www.kslegislature.org",
    jurisdictionId: "ocd-jurisdiction/country:us/state:ks/government",
    unicameral: false,
  },
  {
    code: "KY",
    postal: "ky",
    slug: "kentucky",
    stateName: "Kentucky",
    legislatureName: "Kentucky General Assembly",
    url: "https://legislature.ky.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:ky/government",
    unicameral: false,
  },
  {
    code: "LA",
    postal: "la",
    slug: "louisiana",
    stateName: "Louisiana",
    legislatureName: "Louisiana Legislature",
    url: "https://www.legis.la.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:la/government",
    unicameral: false,
  },
  {
    code: "MA",
    postal: "ma",
    slug: "massachusetts",
    stateName: "Massachusetts",
    legislatureName: "Massachusetts General Court",
    url: "https://malegislature.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:ma/government",
    unicameral: false,
  },
  {
    code: "MD",
    postal: "md",
    slug: "maryland",
    stateName: "Maryland",
    legislatureName: "Maryland General Assembly",
    url: "https://mgaleg.maryland.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:md/government",
    unicameral: false,
  },
  {
    code: "ME",
    postal: "me",
    slug: "maine",
    stateName: "Maine",
    legislatureName: "Maine Legislature",
    url: "https://legislature.maine.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:me/government",
    unicameral: false,
  },
  {
    code: "MI",
    postal: "mi",
    slug: "michigan",
    stateName: "Michigan",
    legislatureName: "Michigan Legislature",
    url: "https://www.legislature.mi.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:mi/government",
    unicameral: false,
  },
  {
    code: "MN",
    postal: "mn",
    slug: "minnesota",
    stateName: "Minnesota",
    legislatureName: "Minnesota State Legislature",
    url: "https://www.leg.mn.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:mn/government",
    unicameral: false,
  },
  {
    code: "MO",
    postal: "mo",
    slug: "missouri",
    stateName: "Missouri",
    legislatureName: "Missouri General Assembly",
    url: "https://www.moga.mo.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:mo/government",
    unicameral: false,
  },
  {
    code: "MS",
    postal: "ms",
    slug: "mississippi",
    stateName: "Mississippi",
    legislatureName: "Mississippi Legislature",
    url: "https://www.legislature.ms.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:ms/government",
    unicameral: false,
  },
  {
    code: "MT",
    postal: "mt",
    slug: "montana",
    stateName: "Montana",
    legislatureName: "Montana Legislature",
    url: "https://leg.mt.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:mt/government",
    unicameral: false,
  },
  {
    code: "NC",
    postal: "nc",
    slug: "north-carolina",
    stateName: "North Carolina",
    legislatureName: "North Carolina General Assembly",
    url: "https://www.ncleg.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:nc/government",
    unicameral: false,
  },
  {
    code: "ND",
    postal: "nd",
    slug: "north-dakota",
    stateName: "North Dakota",
    legislatureName: "North Dakota Legislative Assembly",
    url: "https://www.legis.nd.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:nd/government",
    unicameral: false,
  },
  {
    code: "NE",
    postal: "ne",
    slug: "nebraska",
    stateName: "Nebraska",
    legislatureName: "Nebraska Legislature",
    url: "https://nebraskalegislature.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:ne/government",
    unicameral: true,
  },
  {
    code: "NH",
    postal: "nh",
    slug: "new-hampshire",
    stateName: "New Hampshire",
    legislatureName: "New Hampshire General Court",
    url: "https://gencourt.state.nh.us",
    jurisdictionId: "ocd-jurisdiction/country:us/state:nh/government",
    unicameral: false,
  },
  {
    code: "NJ",
    postal: "nj",
    slug: "new-jersey",
    stateName: "New Jersey",
    legislatureName: "New Jersey Legislature",
    url: "https://www.njleg.state.nj.us",
    jurisdictionId: "ocd-jurisdiction/country:us/state:nj/government",
    unicameral: false,
  },
  {
    code: "NM",
    postal: "nm",
    slug: "new-mexico",
    stateName: "New Mexico",
    legislatureName: "New Mexico Legislature",
    url: "https://www.nmlegis.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:nm/government",
    unicameral: false,
  },
  {
    code: "NV",
    postal: "nv",
    slug: "nevada",
    stateName: "Nevada",
    legislatureName: "Nevada Legislature",
    url: "https://www.leg.state.nv.us",
    jurisdictionId: "ocd-jurisdiction/country:us/state:nv/government",
    unicameral: false,
  },
  {
    code: "NY",
    postal: "ny",
    slug: "new-york",
    stateName: "New York",
    legislatureName: "New York Legislature",
    url: "http://public.leginfo.state.ny.us",
    jurisdictionId: "ocd-jurisdiction/country:us/state:ny/government",
    unicameral: false,
  },
  {
    code: "OH",
    postal: "oh",
    slug: "ohio",
    stateName: "Ohio",
    legislatureName: "Ohio General Assembly",
    url: "https://www.legislature.ohio.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:oh/government",
    unicameral: false,
  },
  {
    code: "OK",
    postal: "ok",
    slug: "oklahoma",
    stateName: "Oklahoma",
    legislatureName: "Oklahoma Legislature",
    url: "https://www.oklegislature.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:ok/government",
    unicameral: false,
  },
  {
    code: "OR",
    postal: "or",
    slug: "oregon",
    stateName: "Oregon",
    legislatureName: "Oregon Legislative Assembly",
    url: "https://www.oregonlegislature.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:or/government",
    unicameral: false,
  },
  {
    code: "PA",
    postal: "pa",
    slug: "pennsylvania",
    stateName: "Pennsylvania",
    legislatureName: "Pennsylvania General Assembly",
    url: "https://www.legis.state.pa.us",
    jurisdictionId: "ocd-jurisdiction/country:us/state:pa/government",
    unicameral: false,
  },
  {
    code: "RI",
    postal: "ri",
    slug: "rhode-island",
    stateName: "Rhode Island",
    legislatureName: "Rhode Island General Assembly",
    url: "https://www.rilegislature.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:ri/government",
    unicameral: false,
  },
  {
    code: "SC",
    postal: "sc",
    slug: "south-carolina",
    stateName: "South Carolina",
    legislatureName: "South Carolina Legislature",
    url: "https://www.scstatehouse.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:sc/government",
    unicameral: false,
  },
  {
    code: "SD",
    postal: "sd",
    slug: "south-dakota",
    stateName: "South Dakota",
    legislatureName: "South Dakota State Legislature",
    url: "https://www.sdlegislature.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:sd/government",
    unicameral: false,
  },
  {
    code: "TN",
    postal: "tn",
    slug: "tennessee",
    stateName: "Tennessee",
    legislatureName: "Tennessee General Assembly",
    url: "https://www.capitol.tn.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:tn/government",
    unicameral: false,
  },
  {
    code: "TX",
    postal: "tx",
    slug: "texas",
    stateName: "Texas",
    legislatureName: "Texas Legislature",
    url: "https://capitol.texas.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:tx/government",
    unicameral: false,
  },
  {
    code: "VA",
    postal: "va",
    slug: "virginia",
    stateName: "Virginia",
    legislatureName: "Virginia General Assembly",
    url: "https://virginiageneralassembly.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:va/government",
    unicameral: false,
  },
  {
    code: "VT",
    postal: "vt",
    slug: "vermont",
    stateName: "Vermont",
    legislatureName: "Vermont General Assembly",
    url: "https://legislature.vermont.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:vt/government",
    unicameral: false,
  },
  {
    code: "WA",
    postal: "wa",
    slug: "washington",
    stateName: "Washington",
    legislatureName: "Washington State Legislature",
    url: "https://www.leg.wa.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:wa/government",
    unicameral: false,
  },
  {
    code: "WI",
    postal: "wi",
    slug: "wisconsin",
    stateName: "Wisconsin",
    legislatureName: "Wisconsin State Legislature",
    url: "https://legis.wisconsin.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:wi/government",
    unicameral: false,
  },
  {
    code: "WV",
    postal: "wv",
    slug: "west-virginia",
    stateName: "West Virginia",
    legislatureName: "West Virginia Legislature",
    url: "https://www.wvlegislature.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:wv/government",
    unicameral: false,
  },
  {
    code: "WY",
    postal: "wy",
    slug: "wyoming",
    stateName: "Wyoming",
    legislatureName: "Wyoming State Legislature",
    url: "https://wyoleg.gov",
    jurisdictionId: "ocd-jurisdiction/country:us/state:wy/government",
    unicameral: false,
  },
];

export const JURISDICTION_BY_CODE: Record<string, Jurisdiction> = Object.fromEntries(
  JURISDICTIONS.map((j) => [j.code, j]),
);
